<?php /** @var \Snowdog\DevTest\Controller\VarnishesAction $this */ ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Varnishes - Cache Warmer</title>

    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/style.css" rel="stylesheet">
</head>

<body>

<?php \Snowdog\DevTest\Component\Menu::getInstance()->render() ?>

<div class="container">
    <?php
    $flashMessage = '';
    if (isset($_SESSION['flash'])) {
        $flashMessage = $_SESSION['flash'];
        unset($_SESSION['flash']);
    }
    ?>
    <p class="bg-info" id="flash-message" <?php if (!$flashMessage): ?> style="display: none;" <?php endif?>><?= $flashMessage ?></p>
    <div>

        <div class="padded">
            <form class="form-inline" method="post" action="/varnish">
                <div class="form-group">
                    <label for="exampleInputName2">IP</label>
                    <input type="text" name="ip" class="form-control" id="exampleInputName2"
                           placeholder="192.168.0.1">
                </div>
                <button type="submit" class="btn btn-primary">Add Varnish</button>
            </form>
        </div>

        <div class="padded">
            <h1>Varnish Assignments</h1>
        </div>

        <?php foreach ($this->getVarnishes() as $varnish): /** @var \Snowdog\DevTest\Model\Varnish $varnish */ ?>
            <?php $websiteIds = $this->getAssignedWebsiteIds($varnish) ?>
            <h2><?= $varnish->getIp() ?></h2>

            <div class="padded">
                <table class="table table-striped">
                    <tr>
                        <th>Associated</th>
                        <th>Name</th>
                        <th>Hostname</th>
                    </tr>
                    <?php foreach ($this->getWebsites() as $website): /** @var \Snowdog\DevTest\Model\Website $website */ ?>
                        <tr>
                            <td><input onclick="linkWebsite(<?= $varnish->getVarnishId() ?>, <?= $website->getWebsiteId()?>, this)" type="checkbox" <?= in_array($website->getWebsiteId(), $websiteIds) ? 'checked="checked"' : '' ?>/></td>
                            <td><?= $website->getName() ?></td>
                            <td><?= $website->getHostname() ?></td>
                        </tr>
                    <?php endforeach ?>
                </table>
            </div>

        <?php endforeach; ?>
    </div>

</div><!-- /.container -->

<script>
    function linkWebsite(varnishId, websiteId, element) {
        let flashMessage = document.getElementById('flash-message');
        flashMessage.style.display = 'none';

        let data = {
            'varnishId': varnishId,
            'websiteId': websiteId,
            'action': element.checked ? 'link': 'unlink'
        };

        let xhr = new XMLHttpRequest();
        xhr.open('POST', '/varnish-link', true);
        xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
        xhr.setRequestHeader('Content-type', 'application/json; charset=UTF-8')

        xhr.onreadystatechange = function () {
            const DONE = 4; // readyState 4 means the request is done.
            const OK = 200; // status 200 is a successful return.
            if (xhr.readyState === DONE) {
                if (xhr.status === OK) {
                    flashMessage.innerHTML = xhr.responseText;
                    flashMessage.style.display = 'block';
                } else {
                    flashMessage.innerHTML = 'Error: ' + xhr.status;
                    flashMessage.style.display = 'block';
                }
            }
        };
        xhr.send(JSON.stringify(data));

        return true;
    }
</script>

</body>
</html>